//This file is generated by Gemini.
'use server';
/**
 * @fileOverview AI-powered personalization flow. It adjusts the layout and content emphasis based on inferred visitor interests.
 *
 * - personalizePortfolio - A function that handles the portfolio personalization process.
 * - PersonalizePortfolioInput - The input type for the personalizePortfolio function.
 * - PersonalizePortfolioOutput - The return type for the personalizePortfolio function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PersonalizePortfolioInputSchema = z.object({
  visitorType: z
    .string()
    .describe(
      'The type of visitor, e.g., recruiter, peer, potential client. This helps in tailoring the content emphasis.'
    ),
  workHistoryWeight: z
    .number()
    .min(0)
    .max(1)
    .default(0.5)
    .describe(
      'Weight for work history section. Higher values emphasize work history more.'
    ),
  skillsWeight: z
    .number()
    .min(0)
    .max(1)
    .default(0.5)
    .describe(
      'Weight for skills section. Higher values emphasize skills more.'
    ),
  projectsWeight: z
    .number()
    .min(0)
    .max(1)
    .default(0.5)
    .describe(
      'Weight for projects section. Higher values emphasize projects more.'
    ),
});
export type PersonalizePortfolioInput = z.infer<typeof PersonalizePortfolioInputSchema>;

const PersonalizePortfolioOutputSchema = z.object({
  layoutEmphasis: z.object({
    workHistoryOrder: z
      .number()
      .describe(
        'The order of the work history section in the layout. Lower numbers indicate higher priority.'
      ),
    skillsOrder: z
      .number()
      .describe(
        'The order of the skills section in the layout. Lower numbers indicate higher priority.'
      ),
    projectsOrder: z
      .number()
      .describe(
        'The order of the projects section in the layout. Lower numbers indicate higher priority.'
      ),
  }).describe('The layout emphasis based on visitor interests.'),
  contentEmphasis: z.object({
    workHistoryHighlight: z
      .string()
      .describe('Specific aspects of work history to highlight.'),
    skillsHighlight: z.string().describe('Specific skills to highlight.'),
    projectsHighlight: z.string().describe('Specific projects to highlight.'),
  }).describe('The content emphasis based on visitor interests.'),
});

export type PersonalizePortfolioOutput = z.infer<typeof PersonalizePortfolioOutputSchema>;

export async function personalizePortfolio(input: PersonalizePortfolioInput): Promise<PersonalizePortfolioOutput> {
  return personalizePortfolioFlow(input);
}

const prompt = ai.definePrompt({
  name: 'personalizePortfolioPrompt',
  input: {schema: PersonalizePortfolioInputSchema},
  output: {schema: PersonalizePortfolioOutputSchema},
  prompt: `You are an AI assistant specializing in personalizing portfolio layouts and content based on visitor type.

Based on the visitor type ({{{visitorType}}}) and the provided weights for work history ({{{workHistoryWeight}}}), skills ({{{skillsWeight}}}), and projects ({{{projectsWeight}}}), determine the optimal layout and content emphasis for a portfolio website.

Consider the following:

- Recruiters typically prioritize work history and relevant skills.
- Peers are often interested in skills and projects.
- Potential clients want to see successful projects and relevant experience.

Return JSON that indicates the order of work history, skills, and projects sections, as well as specific highlights for each section. The order should be determined based on the input weights, with lower numbers indicating higher priority.

Example:
{
  "layoutEmphasis": {
    "workHistoryOrder": 1,
    "skillsOrder": 2,
    "projectsOrder": 3
  },
  "contentEmphasis": {
    "workHistoryHighlight": "Focus on leadership roles and project management experience.",
    "skillsHighlight": "Emphasize front-end development skills and experience with React, Redux, and Material UI.",
    "projectsHighlight": "Showcase projects with significant impact and positive results."
  }
}`, // Added missing curly brace
});

const personalizePortfolioFlow = ai.defineFlow(
  {
    name: 'personalizePortfolioFlow',
    inputSchema: PersonalizePortfolioInputSchema,
    outputSchema: PersonalizePortfolioOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
